/**
 * shell-init.ts — Shell Integration Command
 *
 * Outputs shell hooks for bash/zsh that track terminal session lifecycle.
 * Users add `eval "$(shugo shell-init)"` to their .bashrc/.zshrc.
 *
 * PRINCIPLE: The system should know when a developer starts/stops working.
 */

import { Command } from "commander";

// ── Shell Script ─────────────────────────────────────────────────────────────

const SHELL_SCRIPT = [
  "# ── Shugo Shell Integration ──────────────────────────────────────────────────",
  "# Auto-generated by 'shugo shell-init'. Do not edit manually.",
  '# Add eval "$(shugo shell-init)" to your .bashrc/.zshrc.',
  "",
  '_shugo_session_id=""',
  '_shugo_session_start=""',
  "",
  "_shugo_hook_preexec() {",
  '  _shugo_session_start=$(date +%s)',
  "  command -v shugo >/dev/null 2>&1 && shugo feedback --outcome session-start 2>/dev/null &",
  "  # Show active reminders at session start",
  "  command -v shugo >/dev/null 2>&1 && shugo reminders 2>/dev/null &",
  "  # Send desktop notification for high priority reminders",
  '  if command -v notify-send >/dev/null 2>&1; then',
  '    _shugo_high_reminders=$(shugo reminders --json 2>/dev/null | grep -o \'"priority":"high"\' | wc -l)',
  '    if [ "$_shugo_high_reminders" -gt 0 ]; then',
  '      notify-send "Shugo" "🔴 $_shugo_high_reminders HIGH priority reminder(s) require attention" --urgency=critical 2>/dev/null',
  "    fi",
  "  fi",
  "}",
  "",
  "_shugo_hook_precmd() {",
  '  if [ -n "$_shugo_session_start" ]; then',
  "    local _end=$(date +%s)",
  '    local _duration=$(( _end - _shugo_session_start ))',
  '    if [ "$_duration" -gt 5 ]; then',
  "      command -v shugo >/dev/null 2>&1 && shugo feedback --outcome session-end --duration \"$_duration\" 2>/dev/null &",
  "    fi",
  '    _shugo_session_start=""',
  "  fi",
  "}",
  "",
  "# Zsh hooks",
  'if [ -n "$ZSH_VERSION" ]; then',
  "  autoload -Uz add-zsh-hook 2>/dev/null",
  "  add-zsh-hook preexec _shugo_hook_preexec 2>/dev/null",
  "  add-zsh-hook precmd _shugo_hook_precmd 2>/dev/null",
  "# Bash hooks",
  'elif [ -n "$BASH_VERSION" ]; then',
  "  _shugo_preexec() {",
  "    _shugo_hook_preexec",
  "  }",
  "  _shugo_prompt_command() {",
  "    _shugo_hook_precmd",
  "  }",
  "  trap '_shugo_preexec' DEBUG 2>/dev/null",
  '  PROMPT_COMMAND="_shugo_prompt_command;${PROMPT_COMMAND:-}"',
  "fi",
  "",
  "# ── End Shugo Shell Integration ──────────────────────────────────────────────",
].join("\n");

// ── Command ──────────────────────────────────────────────────────────────────

export const shellInitCommand = new Command("shell-init")
  .description("Output shell hooks for session tracking (add eval to .bashrc/.zshrc)")
  .action(() => {
    process.stdout.write(SHELL_SCRIPT + "\n");
  });
